# Generated by Django 3.2.5 on 2021-08-02 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=144)),
                ('last_name', models.CharField(blank=True, max_length=144)),
                ('email', models.EmailField(max_length=254)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('bio', models.TextField(null=True)),
                ('profile_picture', models.ImageField(upload_to='profiles')),
                ('location', models.CharField(blank=True, max_length=144, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
